### ISSUE TITLE
There is no 'KoGPT2_checkpoint.tar'

### ISSUE THREAD

**Issue by jinh0290** [newfull5/AI_Poet-KoGPT2#1]
KoGPT2_checkpoint.tar 파일을 생성하는 코드가 없네요.
.gitignore에 있는 '.ipynb_checkpoints.ipnyb'에 존재할 것 같은데 
올려주실 수 있으신가요?

**Comment by newfull5** [comment]
저의 보잘것없는 프로젝트에 관심을 가져주셔서 대단히 감사합니다 :D

KoGPT2_checkpoint.tar 파일을 생성하는 코드는 2. Transfer_Learning! 파일 가장 하단에 위치합니다.
![image](https://user-images.githubusercontent.com/52832716/89277519-e3d81000-d67f-11ea-977a-4acf6ae693a0.png)

  
  
저의 역량이 미흡하여 작성자분의 질문을 잘못 이해한 것을, 기초적인 답변을 내놓아 기분을 언짢게하지는 않았을까? 하는 생각이 먼저 들지만,

송구함을 무릅쓰고 말씀드리자면, .ipynb_checkpoints.ipnyb 는 Jupyter Notebook 의 체크포인트 파일입니다.

로컬에서 작업시 코드를 자동 저장합니다, 모델을 포함하지 못합니다. [자세한 설명은 여기 문서를 참고하셔요!](https://stackoverflow.com/questions/46421663/what-are-jupyter-notebook-checkpoint-files-for)

또한 작성자분께서 에러를 마주치게 된 부분이. 아래의 모델 불러오기 코드 부분이라면 
![image](https://user-images.githubusercontent.com/52832716/89281564-3cf67280-d685-11ea-9ee5-f8fea7739aea.png)

해당 셀을 주석 처리하거나 지우고 넘어가셔도 좋습니다. 

해당 부분은 본인이 개발편의상 상단에 배치한 까닭에 재연시 No such file or directory 에러가 뜰 수도 있습니다.

또한 2. Transfer_Learning! 최하단에 있는 셀 또한 같은 이유로, 사전에 학습된 모델이 없는 까닭에 에러가 발생할 수 있습니다.

아래와 같이 수정해주시고 경로설정을 바르게 한다면 재연이 가능할 것 같습니다.

![image](https://user-images.githubusercontent.com/52832716/89282027-e3db0e80-d685-11ea-90f8-f730fbb7ff87.png)


답변이 우답이라는 것을 포함하여 설명이 미흡한 부분이 있다면 말씀해주세요.

부디 도움이 됬으면 하는 바람입니다 :D

**Comment by jinh0290** [comment]
감사합니다!
사실 제가 코드를 제대로 읽지 않고 제가 우문을 한 것인데ㅎㅎ
자세한 설명 정말 감사드립니다!

저는 경험삼아 작은 프로젝트로 시 sns를 만들고 있습니다.
모델은 잘 사용했습니다! 

다시 한 번 감사드립니다ㅎㅎㅎ
